# Generated by Django 4.1.3 on 2022-11-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=100)),
                ('takhasos', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('address', models.CharField(max_length=400)),
                ('nezam_pezeshki', models.PositiveIntegerField()),
                ('phone_number', models.PositiveIntegerField()),
            ],
        ),
    ]
