# Generated by Django 4.1.3 on 2022-11-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctortime_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortime',
            name='day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
