# Generated by Django 4.1.3 on 2022-11-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctortime_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctortime',
            name='reserved',
        ),
    ]
