# Generated by Django 4.1.3 on 2022-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortime',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
