# Generated by Django 4.1.3 on 2022-11-21 12:18

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_doctortime_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortime',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
