# Generated by Django 4.1.3 on 2022-11-16 11:28

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_visitsreserved_reserved_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitsreserved',
            name='day',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
