# Generated by Django 4.1.3 on 2022-11-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('pateints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ins_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.insurance'),
        ),
    ]
