# Generated by Django 4.1.3 on 2022-11-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('pateints', '0002_patient_ins_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ins_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ins_type', to='home.insurance'),
        ),
    ]
